name: Publish VSIX - GitHub

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and cache WASM dependencies
        uses: ./.github/actions/build-wasm-deps
        with:
          build-artifacts-dir: ./media

      - name: Build and Publish
        env:
          VSCE_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        run: |
          npm install
          npm run compile
          npm install -g @vscode/vsce
          vsce package
          for file in ./*.vsix
          do
            vsce publish -p "$VSCE_TOKEN" --packagePath "$file"
            echo "Published VSIX: $file"
          done
          mkdir dist
          mv ./*.vsix dist/

      - name: Upload export artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-release
          path: ./dist/
          compression-level: 1
